In [1]:
import numpy as np
from class_state_vec import state_vector
from class_obs import obs_da
import random as rd
import pandas as pd

infile = 'lorenz63_run.pkl'
sv = state_vector()
sv = sv.load(infile)
x_nature = sv.getTrajectory()
xdim, maxit = np.shape(x_nature)
print('xdim =', xdim)    #row
print('maxit = ', maxit) #column

outfile = 'y_obs.pkl'
obs = obs_da(name = 'observe_full_state')
yo = np.zeros_like(x_nature)
std_nature = np.zeros(xdim)

#compute the standard deviation of each state

for i in range(xdim):
    std_nature[i] = np.std(x_nature[i,:])
    
print('standard deviation of each state = ')
print(std_nature)

#generate synthetic observations

for i in range(xdim):
    yo[i,:] = x_nature[i,:] + np.random.normal(0,np.sqrt(2),maxit)
    

pos = np.zeros_like(yo)
for i in range(maxit):
    pos[:,i] = list(range(0,3))

obs.setVal(yo)
obs.setPos(pos)

print(obs)

#--------------------------------------------------------------------------------
# Store the true and noisy observations
#--------------------------------------------------------------------------------
obs.save(outfile)




xdim = 3
maxit =  8000000
standard deviation of each state = 
[7.93480902 9.01853611 8.6225804 ]
observe_full_state
Position:
[[0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 [2 2 2 ... 2 2 2]]
Time interval:
[0]
values:
[[11.16406581 10.59707959  9.47238684 ... -4.52003295 -4.21116533
  -4.83741255]
 [ 8.53868217 11.04045515 10.39731191 ... -1.50709056 -2.27957562
  -0.84943841]
 [22.10374849 25.21370354 23.39725329 ... 29.09987817 29.46993813
  27.462403  ]]
observe_full_state
